/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OdontologoRouteImport } from './routes/odontologo'
import { Route as DentistAgendaRouteImport } from './routes/dentist.agenda'
import { Route as DentistDashboardRouteImport } from './routes/dentist.dashboard'
import { Route as DentistHorariosRouteImport } from './routes/dentist.horarios'
import { Route as DentistPacientesRouteImport } from './routes/dentist.pacientes'
import { Route as OdontologoConfiguracionRouteImport } from './routes/odontologo.configuracion'
import { Route as PacienteCatalogoRouteImport } from './routes/paciente.catalogo'
import { Route as PacientePanelRouteImport } from './routes/paciente.panel'
import { Route as PacienteAgendarIdRouteImport } from './routes/paciente.agendar.$id'
import { Route as PacienteDentistaIdRouteImport } from './routes/paciente.dentista.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontologoRoute = OdontologoRouteImport.update({
  id: '/odontologo',
  path: '/odontologo',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistAgendaRoute = DentistAgendaRouteImport.update({
  id: '/dentist/agenda',
  path: '/dentist/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistDashboardRoute = DentistDashboardRouteImport.update({
  id: '/dentist/dashboard',
  path: '/dentist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistHorariosRoute = DentistHorariosRouteImport.update({
  id: '/dentist/horarios',
  path: '/dentist/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistPacientesRoute = DentistPacientesRouteImport.update({
  id: '/dentist/pacientes',
  path: '/dentist/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontologoConfiguracionRoute = OdontologoConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => OdontologoRoute,
} as any)
const PacienteCatalogoRoute = PacienteCatalogoRouteImport.update({
  id: '/paciente/catalogo',
  path: '/paciente/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientePanelRoute = PacientePanelRouteImport.update({
  id: '/paciente/panel',
  path: '/paciente/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteAgendarIdRoute = PacienteAgendarIdRouteImport.update({
  id: '/paciente/agendar/$id',
  path: '/paciente/agendar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteDentistaIdRoute = PacienteDentistaIdRouteImport.update({
  id: '/paciente/dentista/$id',
  path: '/paciente/dentista/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/odontologo': typeof OdontologoRouteWithChildren
  '/dentist/agenda': typeof DentistAgendaRoute
  '/dentist/dashboard': typeof DentistDashboardRoute
  '/dentist/horarios': typeof DentistHorariosRoute
  '/dentist/pacientes': typeof DentistPacientesRoute
  '/odontologo/configuracion': typeof OdontologoConfiguracionRoute
  '/paciente/catalogo': typeof PacienteCatalogoRoute
  '/paciente/panel': typeof PacientePanelRoute
  '/paciente/agendar/$id': typeof PacienteAgendarIdRoute
  '/paciente/dentista/$id': typeof PacienteDentistaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/odontologo': typeof OdontologoRouteWithChildren
  '/dentist/agenda': typeof DentistAgendaRoute
  '/dentist/dashboard': typeof DentistDashboardRoute
  '/dentist/horarios': typeof DentistHorariosRoute
  '/dentist/pacientes': typeof DentistPacientesRoute
  '/odontologo/configuracion': typeof OdontologoConfiguracionRoute
  '/paciente/catalogo': typeof PacienteCatalogoRoute
  '/paciente/panel': typeof PacientePanelRoute
  '/paciente/agendar/$id': typeof PacienteAgendarIdRoute
  '/paciente/dentista/$id': typeof PacienteDentistaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/odontologo': typeof OdontologoRouteWithChildren
  '/dentist/agenda': typeof DentistAgendaRoute
  '/dentist/dashboard': typeof DentistDashboardRoute
  '/dentist/horarios': typeof DentistHorariosRoute
  '/dentist/pacientes': typeof DentistPacientesRoute
  '/odontologo/configuracion': typeof OdontologoConfiguracionRoute
  '/paciente/catalogo': typeof PacienteCatalogoRoute
  '/paciente/panel': typeof PacientePanelRoute
  '/paciente/agendar/$id': typeof PacienteAgendarIdRoute
  '/paciente/dentista/$id': typeof PacienteDentistaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/odontologo'
    | '/dentist/agenda'
    | '/dentist/dashboard'
    | '/dentist/horarios'
    | '/dentist/pacientes'
    | '/odontologo/configuracion'
    | '/paciente/catalogo'
    | '/paciente/panel'
    | '/paciente/agendar/$id'
    | '/paciente/dentista/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/odontologo'
    | '/dentist/agenda'
    | '/dentist/dashboard'
    | '/dentist/horarios'
    | '/dentist/pacientes'
    | '/odontologo/configuracion'
    | '/paciente/catalogo'
    | '/paciente/panel'
    | '/paciente/agendar/$id'
    | '/paciente/dentista/$id'
  id:
    | '__root__'
    | '/'
    | '/odontologo'
    | '/dentist/agenda'
    | '/dentist/dashboard'
    | '/dentist/horarios'
    | '/dentist/pacientes'
    | '/odontologo/configuracion'
    | '/paciente/catalogo'
    | '/paciente/panel'
    | '/paciente/agendar/$id'
    | '/paciente/dentista/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OdontologoRoute: typeof OdontologoRouteWithChildren
  DentistAgendaRoute: typeof DentistAgendaRoute
  DentistDashboardRoute: typeof DentistDashboardRoute
  DentistHorariosRoute: typeof DentistHorariosRoute
  DentistPacientesRoute: typeof DentistPacientesRoute
  PacienteCatalogoRoute: typeof PacienteCatalogoRoute
  PacientePanelRoute: typeof PacientePanelRoute
  PacienteAgendarIdRoute: typeof PacienteAgendarIdRoute
  PacienteDentistaIdRoute: typeof PacienteDentistaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontologo': {
      id: '/odontologo'
      path: '/odontologo'
      fullPath: '/odontologo'
      preLoaderRoute: typeof OdontologoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist/agenda': {
      id: '/dentist/agenda'
      path: '/dentist/agenda'
      fullPath: '/dentist/agenda'
      preLoaderRoute: typeof DentistAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist/dashboard': {
      id: '/dentist/dashboard'
      path: '/dentist/dashboard'
      fullPath: '/dentist/dashboard'
      preLoaderRoute: typeof DentistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist/horarios': {
      id: '/dentist/horarios'
      path: '/dentist/horarios'
      fullPath: '/dentist/horarios'
      preLoaderRoute: typeof DentistHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist/pacientes': {
      id: '/dentist/pacientes'
      path: '/dentist/pacientes'
      fullPath: '/dentist/pacientes'
      preLoaderRoute: typeof DentistPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontologo/configuracion': {
      id: '/odontologo/configuracion'
      path: '/configuracion'
      fullPath: '/odontologo/configuracion'
      preLoaderRoute: typeof OdontologoConfiguracionRouteImport
      parentRoute: typeof OdontologoRoute
    }
    '/paciente/catalogo': {
      id: '/paciente/catalogo'
      path: '/paciente/catalogo'
      fullPath: '/paciente/catalogo'
      preLoaderRoute: typeof PacienteCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/panel': {
      id: '/paciente/panel'
      path: '/paciente/panel'
      fullPath: '/paciente/panel'
      preLoaderRoute: typeof PacientePanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/agendar/$id': {
      id: '/paciente/agendar/$id'
      path: '/paciente/agendar/$id'
      fullPath: '/paciente/agendar/$id'
      preLoaderRoute: typeof PacienteAgendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/dentista/$id': {
      id: '/paciente/dentista/$id'
      path: '/paciente/dentista/$id'
      fullPath: '/paciente/dentista/$id'
      preLoaderRoute: typeof PacienteDentistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OdontologoRouteChildren {
  OdontologoConfiguracionRoute: typeof OdontologoConfiguracionRoute
}

const OdontologoRouteChildren: OdontologoRouteChildren = {
  OdontologoConfiguracionRoute: OdontologoConfiguracionRoute,
}

const OdontologoRouteWithChildren = OdontologoRoute._addFileChildren(
  OdontologoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OdontologoRoute: OdontologoRouteWithChildren,
  DentistAgendaRoute: DentistAgendaRoute,
  DentistDashboardRoute: DentistDashboardRoute,
  DentistHorariosRoute: DentistHorariosRoute,
  DentistPacientesRoute: DentistPacientesRoute,
  PacienteCatalogoRoute: PacienteCatalogoRoute,
  PacientePanelRoute: PacientePanelRoute,
  PacienteAgendarIdRoute: PacienteAgendarIdRoute,
  PacienteDentistaIdRoute: PacienteDentistaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
